- name: Restrict Virtual Console Root Logins
  lineinfile:
    path: /etc/securetty
    regexp: '^vc'
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - AC-6(2)

- name: Restrict Serial Port Root Logins
  lineinfile:
    path: /etc/securetty
    regexp: 'ttyS[0-9]'
    state: absent
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - AC-6(2)

- name: List Users
  shell: "cat /etc/passwd | cut -d: -f1"
  register: system_users
  changed_when: False
  check_mode: no
  tags:
  - AC
  - AC-6
  - AC-6(8)

- name: List UIDs
  shell: "cat /etc/passwd | cut -d: -f3"
  register: system_uids
  changed_when: False
  check_mode: no
  tags:
    - AC
    - AC-6
    - AC-6(8)

- name: Ensure that System Accounts Do Not Run a Shell Upon Login
  with_together:
    - "{{ system_users.stdout_lines }}"
    - "{{ system_uids.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    shell: /sbin/nologin
  when: (item.1 < 500) and (item.1 > 0)
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - AC-6(8)

- name: Verify Only Root Has UID 0
  with_together:
    - "{{ system_users.stdout_lines }}"
    - "{{ system_uids.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    state: absent
  when: (item.1 == 0) and (item.0 != "root")
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC
    - AC-6
    - IA
    - IA-2
    - IA-2(1)

- name: Prevent Log In to Accounts With Empty Password - /etc/pam.d/system-auth
  replace:
    path: /etc/pam.d/system-auth
    regexp: nullok
    follow: true
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(c)
    - IA-5(1)

- name: Prevent Log In to Accounts With Empty Password - /etc/pam.d/password-auth
  replace:
    path: /etc/pam.d/password-auth
    regexp: nullok
    follow: true
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(a)
    - IA-5(1)

- name: Find User's With Passwords That Aren't Shadowed
  shell: 'grep -E -v :x:  /etc/passwd | cut -d: -f1'
  register: bad_users
  check_mode: no
  changed_when: False
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(h)

- name: Find Passwords That Aren't Shadowed
  shell: 'grep -E -v :x:  /etc/passwd | cut -d: -f2'
  register: bad_passwords
  changed_when: False
  check_mode: no
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(h)

- name: Verify All Account Password Hashes are Shadowed - /etc/passwd
  with_together:
    - "{{ bad_users.stdout_lines }}"
    - "{{ bad_passwords.stdout_lines }}"
  replace:
    path: /etc/passwd
    regexp: '^{{ item.0 }}:{{ item.1 }}:'
    replace: '{{ item.0 }}:x:'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(h)

- name: Verify All Account Password Hashes are Shadowed - /etc/shadow
  with_together:
    - "{{ bad_users.stdout_lines }}"
    - "{{ bad_passwords.stdout_lines }}"
  user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high

- name: All GIDs referenced in /etc/passwd must be defined in /etc/group
  debug:
    msg: "TO-DO"

- name: Verify No netrc Files Exist
  debug:
    msg: "TO-DO"

- name: Set Password Minimum Length - /etc/login.defs
  lineinfile:
    backup: yes
    path: /etc/login.defs
    regexp: '^PASS_MIN_LEN'
    state: present
    line: 'PASS_MIN_LEN    14'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(a)
    - IA-5(1)

- name: Set Password Minimum Length - /etc/security/pwquality.conf
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^minlen ='
    line: "minlen = 15"
  when: ansible_distribution_major_version == "7"
  tags:
    - CAT-II
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(a)
    - IA-5(1)

- name: Set Password Minimum Age - /etc/login.defs
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    state: present
    line: "PASS_MIN_DAYS     1"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(1)
    - IA-5(d)

- name: Set Password Maximum Age - /etc/login.defs
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    state: present
    line: "PASS_MAX_DAYS     60"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(g)
    - IA-5(1)
    - IA-5(d)

- name: Set Password Warning Age
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    state: present
    line: "PASS_WARN_AGE     7"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - AC
    - AC-2
    - AC-2(2)

- name: Set Failed Login Delay Time
  lineinfile:
    path: /etc/login.defs
    regexp: '^FAIL_DELAY\s+\d+'
    state: present
    line: "FAIL_DELAY   4"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(g)
    - IA-5(1)
    - IA-5(d)

- name: Set Requirement for home directory
  lineinfile:
    path: /etc/login.defs
    regexp: '^CREATE_HOME'
    state: present
    line: "CREATE_HOME   yes"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(g)
    - IA-5(1)
    - IA-5(d)

- name: Set Account Expiration Following Inactivity - EL 6
  lineinfile:
    path: /etc/default/useradd
    regexp: '.*INACTIVE.*'
    line: 'INACTIVE=35'
  when: ansible_distribution_major_version == "6"
  tags:
  - AC
  - AC-2
  - AC-2(2)
  - AC-2(3)

- name: Set Account Expiration Following Inactivity - EL 7
  lineinfile:
    path: /etc/default/useradd
    regexp: '.*INACTIVE.*'
    line: 'INACTIVE=0'
  when: ansible_distribution_major_version == "7"
  tags:
  - AC
  - AC-2
  - AC-2(2)
  - AC-2(3)
  - IA
  - IA-4
  - IA-4(e)

- name: Ensure All Accounts on the System Have Unique Names
  debug:
    msg: "TO-DO"

- name: Assign Expiration Date to Temporary Accounts
  debug:
    msg: "TO-DO"
  tags:
  - AC
  - AC-2
  - AC-2(2)
  - AC-2(3)

- name: Direct root Logins Not Allowed
  shell: echo > /etc/securetty
  args:
    executable: /bin/bash
  when:
  - ansible_distribution_major_version == "7"
  tags:
  - IA
  - IA-2
  - IA-2(1)

- name: Collect users with invalid password expiry
  shell: perl -n -e '($sp_namp,$sp_pwdp,$sp_lstchg,$sp_min,$sp_max) = split(/:/); if ($sp_namp ne "root" && $sp_pwdp ne "!!" && $sp_pwdp ne "*" && ($sp_min < 1 || $sp_max > 60)) { print "$sp_namp\n"; }' < /etc/shadow
  register: accounts_with_bad_expiry

- name: Fix minimum password lifetime
  command: "chage -m 1 {{ item }}"
  with_items: "{{ accounts_with_bad_expiry.stdout_lines }}"
  tags:
    - RHEL-07-010240
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(1)
    - IA-5(d)

- name: Fix maximum password lifetime
  command: "chage -M 60 {{ item }}"
  with_items: "{{ accounts_with_bad_expiry.stdout_lines }}"
  tags:
    - RHEL-07-010250
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - IA
    - IA-5
    - IA-5(f)
    - IA-5(1)
    - IA-5(d)
