- stat:
    path: /etc/yum.repos.d/redhat-rhui.repo
  register: rhui_repo

- name: Ensure audit is Installed
  yum:
    name: audit
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms
  when: rhui_repo.stat.isreg is undefined or rhui_repo.stat.isreg == False

- name: Ensure audit is Installed
  yum:
    name: audit
    state: present
    disablerepo: '*'
    enablerepo: rhui-REGION-rhel-server-releases
  when: rhui_repo.stat.isreg is defined and rhui_repo.stat.isreg == True

- name:  Enable Auditing for Processes Which Start Prior to the Audit Daemon
  shell: /sbin/grubby --update-kernel=ALL --args="audit=1"
  tags:
    - AU
    - AU-14
    - AU-14(1)
    - AU-1
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-10

- name: Get Underlying Architecture for Audit Rules
  shell: getconf LONG_BIT
  register: audit_arch

- name:  Enable Auditing for Processes Which Start Prior to the Audit Daemon
  shell: /sbin/grubby --update-kernel=ALL --args="audit=1"
  tags:
    - AU
    - AU-14
    - AU-14(1)
    - AU-1
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-10


- name: Get Underlying Architecture for Audit Rules
  shell: getconf LONG_BIT
  register: audit_arch
  tags:
    - AU
    - AU-14
    - AU-14(1)
    - AU-1
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-10

- name: Add Audit Rules - init
  copy:
    src: audit-800-53-init.rules
    dest: /etc/audit/rules.d/10-audit-800-53-init.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AU
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-12
    - AU-12(a)
    - AU-12(c)

- name: Add Audit Rules - b32
  template:
    src: audit-800-53-b32.rules.j2
    dest: /etc/audit/rules.d/20-audit-800-53-b32.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AU
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-12
    - AU-12(a)
    - AU-12(c)

- name: Add Audit Rules - b64
  template:
    src: audit-800-53-b64.rules.j2
    dest: /etc/audit/rules.d/30-audit-800-53-b64.rules
  notify: reload auditd
  when: audit_arch.stdout == '64'
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AU
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-12
    - AU-12(a)
    - AU-12(c)

- name: Find commands with setuid/setgid bit set on /
  shell: find / -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
  check_mode: no
  register: find_result

- name:  Ensure auditd Collects Information on the Use of Privileged Commands
  template:
    src: privileged-commands.rules.j2
    dest: /etc/audit/rules.d/40-privileged-commands.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AU
    - AU-1
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-6
    - AU-6(9)
    - AU-12
    - AU-12(a)
    - AU-12(c)

- name: Add Audit Rules - common
  copy:
    src: audit-800-53-common.rules
    dest: /etc/audit/rules.d/50-audit-800-53-common.rules
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AU
    - AU-1(b)
    - AU-2(a)
    - AU-2(c)
    - AU-2(d)
    - AU-2
    - AU-12
    - AU-12(a)
    - AU-12(c)

- name: Configure auditd space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "space_left_action = email"
    regexp: "^space_left_action*"
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - AU
    - AU-1
    - AU-1(b)
    - AU-4
    - AU-5
    - AU-5(b)

- name: Configure auditd admin_space_left Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "admin_space_left_action = single"
    regexp: "^admin_space_left_action*"
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - AU
    - AU-1
    - AU-1(b)
    - AU-4
    - AU-5
    - AU-5(b)

- name: Configure auditd mail_acct Action on Low Disk Space
  lineinfile:
    dest: /etc/audit/auditd.conf
    line: "action_mail_acct = root"
    state: present
  notify: reload auditd
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - CAT-II
    - AU
    - AU-1
    - AU-1(b)
    - AU-4
    - AU-5
    - AU-5(1)
    - AU-5(a)
    - IR
    - IR-5

- name: Configure auditd flush priority
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: '.*flush.*'
    line: flush = data
  when: ansible_distribution_major_version == "7"
  tags:
  - AU
  - AU-9
  - AU-12
  - AU-12(1)

- name: Determine if Log Group (log_group) is Set for Audit Logs
  shell: grep -q ^log_group /etc/audit/auditd.conf
  args:
    executable: /bin/bash
  register: log_group
  when: ansible_distribution_major_version == "6"

- debug:
    var: log_group.stdout

- name: Determine if Log Group (log_group) is not root for Audit Logs
  shell: awk -F "=" '/log_group/ {print $2}' /etc/audit/auditd.conf | tr -d ' '
  args:
    executable: /bin/bash
  register: GROUP
  when:
  - log_group.stdout is defined
  - ansible_distribution_major_version == "6"

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is root (1/4)
  file:
    path: /var/log/audit/audit.log
    mode: 0640
  when:
  - GROUP.stdout is defined
  - GROUP.stdout == "root"
  - ansible_distribution_major_version == "6"
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is root (2/4)
  shell: chmod 0440 /var/log/audit/audit.log.*
  args:
    executable: /bin/bash
  when:
  - GROUP.stdout is defined
  - GROUP.stdout == "root"
  - ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is not root (1/4)
  file:
    path: /var/log/audit/audit.log
    mode: 0600
  when:
  - GROUP.stdout is defined
  - GROUP.stdout != "root"
  - ansible_distribution_major_version == "6"
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is not root (2/4)
  shell: chmod 0400 /var/log/audit/audit.log.*
  args:
    executable: /bin/bash
  when:
  - GROUP.stdout is defined
  - GROUP.stdout != "root"
  - ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is set (3/4)
  shell: chmod 0640 /etc/audit/audit*
  args:
    executable: /bin/bash
  when:
  - log_group.stdout is defined
  - ansible_distribution_major_version == "6"
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is set (4/4)
  shell: chmod 0640 /etc/audit/rules.d/*
  args:
    executable: /bin/bash
  when:
  - log_group.stdout is defined
  - ansible_distribution_major_version == "6"
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is not set (1/4)
  file:
    path: /var/log/audit/audit.log
    mode: 0600
  when:
  - log_group.stdout is defined
  - log_group.stdout == ""
  - ansible_distribution_major_version == "6"
  tags:
    - conf-low
    - conf-medium
    - conf-high
    - int-low
    - int-medium
    - int-high
    - AC-6
    - AC

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is not set (2/4)
  shell: chmod 0400 /var/log/audit/audit.log.*
  args:
    executable: /bin/bash
  when:
  - log_group.stdout is defined
  - log_group.stdout == ""
  - ansible_distribution_major_version == "6"
  ignore_errors: yes
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is not set (3/4)
  shell: chmod 0640 /etc/audit/audit*
  args:
    executable: /bin/bash
  when:
  - log_group.stdout is defined
  - log_group.stdout == ""
  - ansible_distribution_major_version == "6"
  tags:
    - AC
    - AC-6

- name: System Audit Logs Must Have Mode 0640 or Less Permissive when log_group is not set (4/4)
  shell: chmod 0640 /etc/audit/rules.d/*
  args:
    executable: /bin/bash
  when:
  - log_group.stdout is defined
  - log_group.stdout == ""
  - ansible_distribution_major_version == "6"
  tags:
    - AC
    - AC-6

- name: Configure auditd to use audispd's syslog plugin - EL 7
  lineinfile:
    dest: /etc/audisp/plugins.d/syslog.conf
    line: active = yes
    regexp: '.*active.*'
  when: ansible_distribution_major_version == "7"
  tags:
  - AU
  - AU-1
  - AU-3
  - AU-1(b)
  - AU-3(2)
  - IR
  - IR-5

- name: Enable auditd service
  service:
    name: auditd
    state: started
    enabled: yes
