- stat:
    path: /etc/yum.repos.d/redhat-rhui.repo
  register: rhui_repo

- name: Install openswan or libreswan Package
  yum:
    name: "{{ vpn_package }}"
    state: present
    disablerepo: '*'
    enablerepo: rhel-{{ansible_distribution_major_version}}-server-rpms
  when: rhui_repo.stat.isreg is undefined or rhui_repo.stat.isreg == False
  tags:
    - AC
    - AC-17
    - MA
    - MA-4
    - SC
    - SC-8

- name: Install openswan or libreswan Package
  yum:
    name: "{{ vpn_package }}"
    state: present
    disablerepo: '*'
    enablerepo: rhui-REGION-rhel-server-releases
  when: rhui_repo.stat.isreg is defined and rhui_repo.stat.isreg == True
  tags:
    - AC
    - AC-17
    - MA
    - MA-4
    - SC
    - SC-8
