- name: Verify iptables Enabled
  service:
    name: iptables
    state: running
    enabled: yes
  when: ansible_distribution_major_version == 6
  tags:
    - AC
    - AC-4
    - CA
    - CA-3

- name: Check if /etc/sysconfig/iptables exists
  stat:
    path: /etc/sysconfig/iptables
  register: st_ip

- name: Set Default Policy for Incoming Packets
  lineinfile:
    dest: /etc/sysconfig/iptables
    line: ":INPUT DROP [0:0]"
    state: present
    regexp: "^:INPUT ACCEPT.*"
  when: st_ip.stat.exists
  tags:
    - CM
    - CM-7
    - RHEL-06-000120

- name: Set Default iptables Policy for Forwarded Packets
  lineinfile:
    dest: /etc/sysconfig/iptables
    line: ":FORWARD DROP [0:0]"
    state: present
    regexp: "^:FORWARD ACCEPT.*"
  when: st_ip.stat.exists
  tags:
  - RHEL-06-000320
  - CM
  - CM-7

- name: Check if /etc/sysconfig/ip6tables exists
  stat:
    path: /etc/sysconfig/ip6tables
  register: st_ip6

- name: RHEL-06-000523 Set Default ip6tables Policy for Incoming Packets
  lineinfile:
    dest: /etc/sysconfig/ip6tables
    line: ":INPUT DROP [0:0]"
    state: present
    regexp: "^:INPUT ACCEPT.*"
  when: st_ip6.stat.exists
  tags:
    - RHEL-06-000523
    - CM
    - CM-7
